<?php
namespace iAvatar777\components\FormatterRus;

use iAvatar777\services\DateRus\DateRus;
use yii\base\Component;
use yii\helpers\StringHelper;
use yii\helpers\VarDumper;
use yii\i18n\Formatter;

class FormatterRus extends Formatter
{
    public function asDate($value, $format = null)
    {
        if (StringHelper::startsWith($format,'php:')) {
            $format1 = substr($format,4);
            $f1 = DateRus::format($format, $value);
            $format = 'php:' . $f1;
            VarDumper::dump([$value, $format]);
        }

        return parent::asDate($value, $format); // TODO: Change the autogenerated stub
    }

    public function asDatetime($value, $format = null)
    {
        if (StringHelper::startsWith($format,'php:')) {
            $format = DateRus::format($format, $value);
        }

        return parent::asDatetime($value, $format); // TODO: Change the autogenerated stub
    }


}