<?php
namespace iAvatar777\components\FormatterRus;

use iAvatar777\services\DateRus\DateRus;
use yii\base\Component;
use yii\helpers\StringHelper;
use yii\helpers\VarDumper;
use yii\i18n\Formatter;

class FormatterRus extends Formatter
{
    public function format($value, $format)
    {

        return parent::format($value, $format); // TODO: Change the autogenerated stub
    }

    public function asDate($value, $format = null)
    {
        if (StringHelper::startsWith($format,'php:')) {
            $format1 = substr($format,4);
            $f1 = DateRus::format($format1, $value);
            $format = 'php:' . $f1;
        }

        return parent::asDate($value, $format); // TODO: Change the autogenerated stub
    }

    public function asDatetime($value, $format = null)
    {
        if (is_null($format)) {
            VarDumper::dump($this->datetimeFormat);
        }
        if (StringHelper::startsWith($format,'php:')) {
            $format1 = substr($format,4);
            $f1 = DateRus::format($format1, $value);
            $format = 'php:' . $f1;
        }

        return parent::asDatetime($value, $format); // TODO: Change the autogenerated stub
    }

    public function asTimestamp($value, $format = null)
    {
        if (StringHelper::startsWith($format,'php:')) {
            VarDumper::dump([$value, $format]);
            $format1 = substr($format,4);
            $f1 = DateRus::format($format1, $value);
            $format = 'php:' . $f1;
        }

        return parent::asTimestamp($value); // TODO: Change the autogenerated stub
    }
}